name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Linux packages
        run: |
          sudo apt install libvips-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"

      - name: Install Gems
        run: |
          bundle install

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 22.22.2

      - name: NPM install
        run: |
          npm install

      - uses: limjh16/jekyll-action-ts@v2

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          enable_cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # publish_branch: master
